### ISSUE TITLE
CTM is missing on Serverside

### ISSUE THREAD

**Issue by ststeppat** [Siepert123/create-legacy#35]
Hello,
Create 1.12.2-0.1.0a crash the Server. CTM is installed, no Problems with create-24w37a.

Time: 28.10.24 17:16
Description: Exception in server tick loop

Missing Mods:
	unknown : need any: have missing

net.minecraftforge.fml.common.MissingModsException: Mod create (Create Legacy) requires [ctm]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:750)

**Comment by Siepert123** [comment]
It should be fixed now, could you please test with the newest patch?

**Comment by ststeppat** [comment]
The same Crash:

Time: 01.11.24 13:22
Description: Exception in server tick loop

Missing Mods:
	unknown : need any: have missing

net.minecraftforge.fml.common.MissingModsException: Mod create (Create Legacy) requires [ctm]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:750)


The Installed Version of CTM:
https://www.curseforge.com/minecraft/mc-mods/ctm

**Comment by Doggysus** [comment]
having same error

 [18:57:55] [Server thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod create (Create Legacy) requires [ctm]
[18:57:55] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.MissingModsException: Mod create (Create Legacy) requires [ctm]	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572) ~[Loader.class:?]	
at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1802) [MinecraftServer.class:?]
		at java.lang.Thread.run(Thread.java:750) [?:1.8.0_432]
[18:57:55] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /var/lib/pufferpanel/servers/db5ff4b8/./crash-reports/crash-2024-11-02_18.57.55-server.txt
[18:57:55] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server

CTM version: https://www.curseforge.com/minecraft/mc-mods/ctm/files/2915363

**Comment by aking4125** [comment]
Same issue. Only 24w37a of this mod works on the server without issues. CTM is installed server side and still crashes requiring CTM.

Single Player works fine.

[crash-2024-11-02_13.31.37-server.txt](https://github.com/user-attachments/files/17607810/crash-2024-11-02_13.31.37-server.txt)

**Comment by Siepert123** [comment]
Yeah that was my bad idk what I was doing but I made MysticalLib clientside only instead of CTM sorry, should be really all good this time 😅
